resources:
  - name: uploadArtifact_gitRepoResource
    type: GitRepo
    configuration:
      gitProvider: aidan_github
      path: a-murphy/UploadArtifact
      branches:
        include: '^{{gitBranch}}$'
  - name: uploadArtifact_filespec
    type: FileSpec
    configuration:
      sourceArtifactory: aidan_artifactory
  - name: uploadArtifact_remoteFile
    type: RemoteFile
    configuration:     
      source: aidan_aws
      fileLocation: s3://jfrog-shippable-aidan/fakelogs
      fileName: ${current_date}-1.txt
  

pipelines:
  - name: UploadArtifactPipeline
    steps:
      - name: determine_file
        configuration:
          targetPath: "example-repo-local/testArtifactUpload/${run_id}"
          sourcePath: "pipelines.yml"
          integrations:
            - name: aidan_artifactory
          outputResources:
            - name: uploadArtifact_remoteFile
        execution:
          onExecute:
            - write_output uploadArtifact_remoteFile fileName="$(date "%Y-%m-%d")-1.txt"
      - name: upload_file
        type: UploadArtifact
        configuration:
          targetPath: "example-repo-local/testArtifactUpload/${run_id}"
          sourcePath: "pipelines.yml"
          integrations:
            - name: aidan_artifactory
          inputResources:
            - name: uploadArtifact_gitRepoResource
          inputSteps:
            - name: upload_tar
      - name: upload_tar
        type: UploadArtifact
        configuration:
          targetPath: "example-repo-local/testArtifactUpload/${run_id}"
          integrations:
            - name: aidan_artifactory
          inputResources:
            - name: uploadArtifact_remoteFile
