resources:
  - name: uploadArtifact_trigger
    type: CronTrigger
    configuration:
      interval: 0 0 * * * *
  - name: uploadArtifact_filespec
    type: FileSpec
    configuration:
      sourceArtifactory: aidan_artifactory
  - name: uploadArtifact_remotefile
    type: RemoteFile
    configuration:     
      source: aidan_aws
      fileLocation: s3://jfrog-shippable-aidan/fakelogs
      fileName: ${current_date}-1.txt
  

pipelines:
  - name: UploadArtifactPipeline
    steps:
      - name: determine_file
        type: Bash
        configuration:
          inputResources:
            - name: uploadArtifact_trigger
        execution:
          onExecute:
            - add_run_variables current_date=$(date +%Y-%m-%d)
      - name: upload
        type: UploadArtifact
        configuration:
          targetPath: "example-repo-local/testArtifactUpload/"
          integrations:
            - name: aidan_artifactory
          inputSteps:
            - name: determine_file
          inputResources:
            - name: uploadArtifact_remotefile
          outputResources:
            - name: uploadArtifact_filespec
      - name: download_filespec
        type: Bash
        configuration:
          inputResources:
            - name: uploadArtifact_filespec
        execution:
          onExecute:
            - cat $res_uploadArtifact_filespec_resourcePath/**/*.txt
